### ISSUE TITLE
Volume not changing for Windows Media Player

### ISSUE THREAD

**Issue by ChineseOuchie** [omriharel/deej#1]
I can see the slide going up and down in the volume mixer of Windows 10, but the volume doesn't change. Inside Windows Media Player there is also slider which is at the same position as the W0. But when changing the W10 slider it doesn't change the WMP slider.

Therefore the volume won't change.

It does work for the "master" volume

**Comment by omriharel** [comment]
Hi there, thanks for writing; I don't have Windows Media Player installed, would you be able to provide a video capture of what you're seeing?

I'd also appreciate a screenshot of your task manager's "details" tab while this is occurring, as well as your `config.yaml`. Thanks!

**Comment by ChineseOuchie** [comment]
As you can see here: https://imgur.com/j3yIKX7
When changing the volume inside my WMP it automatic changes the W10 as well, but when I use the physical it won't change the volume of my program.

Here is the task manager: https://imgur.com/undefined
Config file: https://imgur.com/QIpqwch

**Comment by omriharel** [comment]
So to clarify:

- You're seeing that moving the real-world slider sets the WMP volume in the Windows Mixer, but _not_ in the app itself
- Moving the virtual volume slider in WMP also sets its volume in the Windows Mixer

If those are right, would you also be able to test if moving WMP's slider in the Windows Mixer affects or doesn't affect WMP's own volume slider?

**Comment by ChineseOuchie** [comment]
Yes it does change the WMP slider when moving it in Windows mixer.
Both slider are linked with each other

See link: https://imgur.com/IsRQW9u

**Comment by omriharel** [comment]
Oof, this is rather perplexing.

I suspect that WMP has its own volume hook that responds to volume change events (to its audio session's `SimpleAudioVolume`) as explained here: https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-isimpleaudiovolume-setmastervolume

However, `deej` currently doesn't provide an event context GUID to its SetMasterVolume call:

```python
session.SimpleAudioVolume.SetMasterVolume(value, None)
```

So what I assume is happening is that WMP isn't actually notified by that volume change event, or ignores it. If this is true, it means WMP manages its own volume separately from its audio session's volume (by just syncing to it on volume change). The solution would be passing a valid GUID there, but I'm not sure how to do this yet. If anyone has any inputs, your help is appreciated!

I'll also look a bit further into this when I have time, but for now I'm leaving this one open and suggesting (for the time being) that you use another video player like VLC.

**Comment by omriharel** [comment]
So I looked a bit more into it, and I think I figured out how to pass that event context GUID. I pushed commit 8134a05, could you please pull and see if that fixes it for you?

In my testing here, Windows Media Player worked fine both with _and_ without this change, so I'm not sure what's going on.

**Comment by ChineseOuchie** [comment]
Can confirm it works!

**Comment by omriharel** [comment]
That's lunch then.

**Comment by omriharel** [comment]
That's lunch then.

**Comment by omriharel** [comment]
That's lunch then.

**Comment by ChineseOuchie** [comment]
On another note. You can make this work on python 3 if you change the following:

Line 82:   split_line = line.decode("utf-8").split('|')
196:         for slider_idx, targets in self._settings['slider_mapping'].items():
239:         for process_name, process_sessions in self._sessions.items():
278:         print (s)

**Comment by omriharel** [comment]
I'll get to it someday, I know that it's a must :P
