### ISSUE TITLE
Community/Dimitar schematic is wrong

### ISSUE THREAD

**Issue by frankrpeters** [omriharel/deej#102]
The schematic in assets/community-builds/extra is wrong and should not be used. If you wire your device in this way, you will short out your power source if you simultaneously turn up the voulme of any channel to full and mute it. Since this should be caught by the USB shortout protection for devices over USB, I would, however, not expect permanent damage in most cases.

The correct wiring would be to swap the connections of pins 2 and 3 for every switch. This would lead to pull down the potential of the corresponding input instead of leaving it floating when muted, At the same time it would prevent the switch to bridge the "lower half" of the poti.

I would assume that this is what Dimitar intended, however, this is not currently reflected in the schematic.

**Comment by omriharel** [comment]
Hi @frankrpeters, thanks for writing and for the report! Unfortunately I don't have a great way to change the sketch files as they were provided by Dimitar as-is, but I'll link to your explanation near those links in a future edit. Thanks again!

**Comment by frankrpeters** [comment]
Hi,

if you can wait some time, I'll probably get around to edit the files myself and send you the changed files. 

Regards, Frank


Am 19. April 2024 12:50:35 MESZ schrieb Omri Harel ***@***.***>:
>Hi @frankrpeters, thanks for writing and for the report! Unfortunately I don't have a great way to change the sketch files as they were provided by Dimitar as-is, but I'll link to your explanation near those links in a future edit. Thanks again!
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/omriharel/deej/issues/102#issuecomment-2066320574
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by omriharel** [comment]
Thanks, you can post them here and whoever follows the link will find them here - I'd rather have that documented in this way rather than change the files provided by the original author.
