### ISSUE TITLE
Bind buttons to change output device/media controls

### ISSUE THREAD

**Issue by mat-tgn** [omriharel/deej#103]
is possible to bind a button to output device change / next / prev ?

**Comment by mkotek** [comment]
see this forked repo: https://github.com/Miodec/deej

**Comment by omriharel** [comment]
Hi @mat-tgn, thanks for writing. Button support isn't currently built into deej - there are future plans to eventually include it, but nothing that's fully solidified yet.

In the meantime you can either use a board with HID support to act as a keyboard extension (this can run side-by-side with the original version of deej, as HID and serial don't conflict with one another - but you do need to essentially build your own Arduino sketch that handles both of these parts) - or a fork which adds this to the serial interface such as the one linked above by @mkotek.
