### ISSUE TITLE
Application cannot run automatically at startup

### ISSUE THREAD

**Issue by DHDANI** [omriharel/deej#104]
I can't make the app autostart, even if I put it into shell:startup, or create a task with task scheduler. It requires me to click on the shortcut. Using Windows 11.

**Comment by ChxRagnar** [comment]
Sadly I'm in the same boat. Cant get it to auto start. Works great with just opening the exe but Windows cant open it automatically. 

Edit: Found the issue. The Deej Folder was read only because I put it in Program Files, Moved it to C: and its working now

**Comment by omriharel** [comment]
Hi @DHDANI, thanks for writing.

To have deej run on startup, please make sure that it's placed together with the config file in a directory that does not require any special permissions (for example, don't use Program Files). Then create a shortcut to `deej.exe`, and move the shortcut into `shell:startup`. The shortcut is set to start in the original location of deej.exe, which is how deej is able to locate its config file.

**Comment by Ylambers** [comment]
The only location where the autostart works for me is` C:\sound-control\deej.exe`. It doesn’t work when placed directly in the startup folder or on a different hard drive. Of course, I created new shortcuts for each location.

**Comment by jmerdich** [comment]
Note that the default config path is relative to where the program was started.

For task scheduler in particular, the program starts in System32 by default. Make sure you set `Start in (optional)` to the folder where your config file is at (or where deej.exe is for what you get from cmd by default).
