### ISSUE TITLE
Max slider value is not adjustable

### ISSUE THREAD

**Issue by LovroG05** [omriharel/deej#105]
I run this on an esp32, and when i max the sliders, it returns 4095, which gets flagged as a dirty line. This means i can only use 1/4 of my slider. 

Can you please add this to the config? 
If you want, i can code it and PR

thanks

**Comment by I3lackRacer** [comment]
I made a fix on the Arduino's side, if you want I can open a merge request.

**Comment by I3lackRacer** [comment]
Ok, just found out that according to the [CONTRIBUTING.md](https://github.com/omriharel/deej/blob/9c0307b96341538ec46f18d2e9b18aaa84441175/docs/CONTRIBUTING.md) PRs will not be merged. Hope he will add this feature in the future. 😊

**Comment by tanishqmanuja** [comment]
https://github.com/tanishqmanuja/deej/commit/282f79d9855b3370c0c501a2806eff579f0538f2

**Comment by omriharel** [comment]
Hi there @LovroG05, thanks for writing. There are no current plans to allow a configurable range of values for the serial interface - the expectation is that devices with a 12-bit ADC instead map the values to the 0-1023 range used in the default Arduino sketch. There is [`map()` function](https://www.arduino.cc/reference/en/language/functions/math/map/) in Arduino to allow you to easily do that.

Putting this as a config option will ultimately result in users attempting to tweak it to try and solve issues that originate in incorrect wiring, faulty pots, etc. - and thus will also make it more difficult to help them with troubleshooting.
