### ISSUE TITLE
Ready to use purchasable controllers?

### ISSUE THREAD

**Issue by Eiion** [omriharel/deej#116]
Are there cheap/very affordable devices that can be purchased and are widely available which are compatible with deej?

**Comment by omriharel** [comment]
Hi there @Eiion - deej is a non-commercial project intended for a DIY audience, and as such I won't be pointing you towards anything of this sort. That being said I don't control what others choose to do around the project, so inevitably some people are going to be selling hardware. However I ask that you don't discuss it on this public platform, as I prefer not to promote this type of thing. Please also be aware that our community Discord server would not be an appropriate space for it either. Thank you.

**Comment by Eiion** [comment]
Not even the discord server, where you could create a channel to allow people discussing commercial products that are compatible - with the role to not post store links? Where else should we discuss it, a place where users of the software meet? While I get your point this seems highly limiting to your own project as not everyone has the needed tools to assemble the hardware as intended or even print a case. If there's affordable compatible devices you should give that a space the discuss them. I hope you'll reconsider your current point of view on that.

**Comment by omriharel** [comment]
Hi @Eiion, while I understand the possible frustration around this decision I feel that it is reasonable for me to set the spirit and intended direction for a project in this manner. I'm not prohibiting the very notion of ready made devices, I'm simply asking users that are interested in them to do their research independently. 

It's worth mentioning that you do not need expensive soldering equipment or a 3D printer to make a functional and nice looking deej build either - you're welcome to look in our community showcase for some creative examples of builds made fully using a breadboard or out of. cardboard. I made my first iteration of this project using a shoebox.

I hope this inspires you to look in the DIY direction, but if you wish to still go with readily made hardware then please seek it independently. Thank you.
