### ISSUE TITLE
Pause music for a specific app

### ISSUE THREAD

**Issue by enrigisbert** [omriharel/deej#12]
is it possible to add an option that sends a pause command when the volume is lower that some  %? that would be great when you mute spotify it pauses

**Comment by omriharel** [comment]
Hi @enrigisbert, thanks for writing!

Unfortunately the traditional media-key-based pause/play approach cannot target a single application, so if we did that it would also send a "play/pause" to any other media app such as your web browser.

The idea of triggering certain things upon hitting a volume threshold for a particular app does sound like it could have other valid uses, and I'll be considering it for a future update (some time after we have infrastructure-level support for triggers in response to a button push or toggle switch).
