### ISSUE TITLE
deej doesn't work after windows update

### ISSUE THREAD

**Issue by Frstikowl** [omriharel/deej#126]
deej stopped working. Until one moment everything was just fine. Now, when I launch the program, it does not see the sliders, although everything is configured correctly, restarting also does not help.
![Снимок экрана 2024-11-20 192941](https://github.com/user-attachments/assets/2ce63d17-c681-4183-92b7-aed91e2ebfbd)

**Comment by 24pmabb8** [comment]
Similar issue.  Tried multiple COM ports, connects successfully.  Reuploaded sketch to the Arduino.  IDE Serial Monitor shows potentiometers responding.  Re-downloaded deej executable, put in new directory w/ new config.  Volume adjustment not working.

Win10, only changes to system are 2 recent Windows Updates (KB5046542 & KB5046613)

**Comment by Frstikowl** [comment]
I rolled back the operating system to the last restore point that was automatically created before the update. Everything worked, apparently the new patch "wch.cn-Ports-3.9.2024.9" is to blame. I'm using Windows 11.
![Снимок экрана 2024-11-20 233010](https://github.com/user-attachments/assets/d60db383-4eb5-4091-a631-47b562e62105)

**Comment by 24pmabb8** [comment]
It's a driver issue.  Was able to resolve by reinstalling the older driver (roll back was not available for me).  Device Manager > Ports (COM & LPT).  Find the COM port associated with the Arduino.  

Recent Win Update updated the CH340 driver to newer version dated this year.  You can do a web search for an older one.  I found one dated 2019.  Deej working again after driver update.

**Comment by Frstikowl** [comment]
Thank you very much, now everything works.

**Comment by richardjharding** [comment]
Same here on win11 - open device manager and click the "rollback driver" to previous version fixed it for me
