### ISSUE TITLE
Two way communication? 

### ISSUE THREAD

**Issue by crosma** [omriharel/deej#14]
Does deej have the ability to send volume changes to the arduino? I want to build one with motorized potentiometers. I had a look at the go code but I don't have any experience with it and got lost.

**Comment by omriharel** [comment]
Hi @crosma, thanks for writing!

Two-way serial communications might be implemented into deej in the future (it's on the long term roadmap), as they enable a whole range of new hardware capabilities. That being said, adding this might break compatibility for existing users so I'm not planning to do it in the near future (and when I do decide to implement it, there'll be ample prior notice and an opt-out solution).

To support motorized sliders, you'd also need to receive volume change events from the host OS (which I haven't looked into as of writing this). deej doesn't currently have a way to do this.

Existing community-driven efforts to support two-way communications have been made by several people, most notably the excellent @jax-b in his fork of deej. You're welcome to take a look there if you want more details.
