### ISSUE TITLE
deej crashes everytime i try to start it 

### ISSUE THREAD

**Issue by Gongal66** [omriharel/deej#2]
Here is the error message:

Exception occurred: 'NoneType' object has no attribute 'lower'
Traceback: Traceback (most recent call last):
  File "deej.py", line 296, in main
    deej.start()
  File "deej.py", line 100, in start
    self._apply_volume_changes()
  File "deej.py", line 209, in _apply_volume_changes
    sessions = self._acquire_target_sessions(target)
  File "deej.py", line 240, in _acquire_target_sessions
    if process_name.lower() == name.lower():
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by omriharel** [comment]
Hi there! Thanks for writing. Can you please attach your `config.yaml` file?

**Comment by Gongal66** [comment]
# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
slider_mapping:
  0: master
  1: discord.exe
  2: opera.exe
  3: spotify.exe
  4: 

# recommend to leave this setting at its default value
process_refresh_frequency: 5

# settings for connecting to the arduino board
com_port: COM4
baud_rate: 9600

**Comment by omriharel** [comment]
The issue you're having stems from having nothing set for slider #5 (index 4). You have two options here:

- If you do have a fifth slider in your build, put `none` for the key `4` (e.g. `4: none`)
- If you don't have one, remove the line

Please let me know if this fixes the problem. If you need further help please reach out!

**Comment by Gongal66** [comment]
Now that error dont appear, but doesnt do anything at all. Before, one sec before the error appear sometimes worked a little. Gonna try to reinstall it to see if it fixes

**Comment by omriharel** [comment]
Alright. If you'd like me to guide you through it, feel free to reach out. We can talk on Discord if you need, just let me know your handle

**Comment by Gongal66** [comment]
IT WORKS!!!!!! I reinstalled it and now works like a charm, really thanks for share this cool project!!

**Comment by omriharel** [comment]
You're welcome! Feel free to send me a few pics of what you've built if you'd like to share, and I'll add them to the build showcase. Regardless, hope you'll enjoy it!
