### ISSUE TITLE
Volume doesn't go all the way to 0 or 100%

### ISSUE THREAD

**Issue by nokarukuta** [omriharel/deej#20]
I have some cheap sliders so the values in serial monitor don't go all the way. The lowest I can get it is 22 and the top sometimes barely makes it to 950. Is there a value I can change that accounts for that? It shouldn't be a problem but it turns out that even at 2% volume in Volume mixer stuff applications are still audible.

**Comment by omriharel** [comment]
Hi @nokarukuta, thanks for writing.

There are two things you could try:

- setting `noise_reduction` in your config file to `high` would make your volume adjust at 4% increments. This may be sufficient for ~22 in serial monitor to count as a 0.
- alternatively, if you're comfortable manually editing the Arduino sketch, you could use the `map` function to remap the values of your sliders from the range you're seeing to 0-1023.

That aside, are you sure you've wired up your sliders correctly? This shouldn't really happen unless one or more analog pins are subject to some signal noise.

Also, please feel free to join our Discord server if you'd like more active help troubleshooting - GitHub can be a bit of a tricky platform for that :)

**Comment by nokarukuta** [comment]
Thank you very much for the quick response!
The noise_reduction setting is something I've tried before and it didn't help. Anyway I tried editing the sketch: 

```
void updateSliderValues() {
  for (int i = 0; i < NUM_SLIDERS; i++) {
     analogSliderValues[i] = analogRead(analogInputs[i]);
     analogSliderValues[i] = map(analogSliderValues[i], 25, 950, 0, 1023);
  }
}
```
But it seems that I'm doing something wrong since only the first slider now works in deej. Which is strange because all 5 values in Serial Monitor show the remapped numbers.

**Comment by omriharel** [comment]
Hey @nokarukuta,

The values you're giving as an example aren't properly constrained to be a 10-bit number. Values sent to deej must always be between 0 and 1023. Try adding the following line after the `map` statement: `analogSliderValues[i] = constrain(analogSliderValues[i], 0, 1023);

**Comment by nokarukuta** [comment]
Well that fixed it! Thank you very much for your time and for making this project! It's one of those thing you never knew you needed, but are so useful you can never go back after having them
