### ISSUE TITLE
[Feature] Change the app's devices

### ISSUE THREAD

**Issue by lando-cal** [omriharel/deej#25]
As someone who has to juggle/mux my audio quite often to patch certain media to certain apps on the fly (for instance, I'll have someone on Skype and someone on Discord, and route them together, and occasionally want to share the audio from a video to one or both of them) I use a shortcut to the `ms-settings:apps-volume` URI. It would be great if I could add some buttons to my DEEJ to select the active sources for each slider instead!

**Comment by omriharel** [comment]
Hi @lando-cal, thanks for writing. This isn't supported by Windows Core Audio APIs and as such is out-of-scope for the project. Please see more details in #22 if you're interested!
