### ISSUE TITLE
"mic" slider doesn't affect capture level with some microphones

### ISSUE THREAD

**Issue by Kwimbee** [omriharel/deej#26]
Hey,

Amazing project ! I love it !

Theres a small issue i'm having, the mic mapping doesnt seem to work for me.

Here's my slider mapping :

```
slider_mapping:
  0: chrome.exe
  1: 
    - discord.exe
    - skype.exe
    - zoom.exe
    - teams.exe
  2: 
    - tidal.exe
    - tidalplayer.exe
    - spotify.exe
  3: 
    - rustclient.exe
    - planetside2_x64.exe
    - planetside2_x64_BE.exe
  4: vlc.exe
  5: deej.unmapped
  6: mic
```

All is working fine, but the mic volume doesn't move. I've also tried the following mapping, without success : 

```
slider_mapping:
  0: chrome.exe
  1: 
    - discord.exe
    - skype.exe
    - zoom.exe
    - teams.exe
  2: 
    - tidal.exe
    - tidalplayer.exe
    - spotify.exe
  3: 
    - rustclient.exe
    - planetside2_x64.exe
    - planetside2_x64_BE.exe
  4: vlc.exe
  5: deej.unmapped
  6: Microphone (AUKEY PC-LM1 USB Microphone)
```

Anything I should check ? This is what I've already checked: 

- Running release-v0.9.10
- Value for the corresponding slider is well received on the serial port
- When running deej in debug mode and moving the mic slider, i receive the following lines in the console : 
  `2021-01-06 22:40:02.375 DEBUG   deej.sessions.mic               Adjusting session volume        {"to": "1.00"}`
- Audio sessions seem to be found for the mic, as stated by the following console output : 
  `2021-01-06 22:42:08.930 DEBUG   deej.session_finder             Enumerated device info  {"deviceIdx": 4, "deviceDescription": "microphone", "deviceFriendlyName": "Microphone (AUKEY PC-LM1 USB Microphone)", "dataFlow": 1}`
  `2021-01-06 22:42:08.931 DEBUG   deej.sessions.device.microphone Created audio session instance  {"session": "<session: Microphone (AUKEY PC-LM1 USB Microphone), vol: 1.00>"}`
- Microphone (AUKEY PC-LM1 USB Microphone) is set as my default audio input

**Comment by Kwimbee** [comment]
I've just done another test, and what's interesting is that the slider in the sound properties window does move perfectly, but the mic volume is not altered.

See the following image for reference : 

![image](https://user-images.githubusercontent.com/72341571/103824458-3d4fcb00-5074-11eb-82bb-18fa35891bc2.png)

Noise still goes into discord, and green volume bars are present in the windows dialog, although the level of the mic is set at 0 by deej.

**Comment by omriharel** [comment]
Hi @Kwimbee, thanks for writing!

This appears to be an issue with some USB and bluetooth microphones where they disobey that "level" slider entirely. You can try it out by closing deej and moving that slider in the properties screen from this above screenshot, and you'll see that it has no effect on mic capture level.

My guess is that the driver software for these devices either hasn't implemented proper support for that Windows API, or that they're ignoring it knowingly and purposefully. In both cases, I'm afraid you'll need to try a different mic if you'd want deej to work with it as-is.

Your other option is to add Windows-side muting (with the `SetMute` function) into deej, and enable it for anything that becomes zeroed out. This isn't implemented in deej yet, so you'll need to get your hands dirty if you go that route! If you do that, make sure that muting does actually work with your mic (that little button next to the volume level textbox).

**Comment by Kwimbee** [comment]
Hi @omriharel,

Thanks for the explanation. This is a "cheap" USB webcam so yeah I wouldn't be surprised if the driver is not perfect.

Regarding the use of the SetMute function, I'm not too fluent in Go and I don't know the Windows API regarding audio stuff, so I don't really trust myself doing it.

Is this something that is on the deej roadmap ?

**Comment by omriharel** [comment]
Hey @Kwimbee, thanks for your reply.

This is not currently on the roadmap, because muting doesn't inherently represent what the average user would want as their zero state (even though muting is indeed equivalent to zero volume, semantically speaking).

It's entirely possible that muting will be added as its own core concept at a future time, and that will likely be tied to something more binary like a button or toggle switch.
