### ISSUE TITLE
Motorized slider?

### ISSUE THREAD

**Issue by Pawnerd** [omriharel/deej#28]
Hi, This is an awesome project! Recently I finished the hardware (pcb+casing) of a motorized slider. Is there any wish for Deej to also support motorized sliders instead of only manual ones? This could allow a slider to preview the volume of an app if it's changed from another source than the slider itself.

Here is a video: https://www.reddit.com/r/MechanicalKeyboards/comments/kz9j17/i_have_been_working_on_a_new_product_for_a_while/

**Comment by omriharel** [comment]
Hi there @Pawnerd, thanks for writing.

Please check out my response to #14 - I still have no current plans to support motorization in deej's main fork, because it's a relatively niche use-case and I prefer to keep things simple at this time.
