### ISSUE TITLE
can you add the key for volume mute and the key for mute microphone?

### ISSUE THREAD

**Issue by RssFra97** [omriharel/deej#30]
Good evening,
I'm so interested in this project, but can you add two keys, one for total volume mute and one for microphone mute?

**Comment by omriharel** [comment]
Hi there, thanks for writing.

There isn't any official support for buttons planned at the moment, but plenty of people have built and made available versions of deej that do have it in some form. 

Please check out the variety of builds in the project's community showcase (linked from our homepage) or join the community Discord servers if you have more questions about building your own. Thanks!

**Comment by RssFra97** [comment]
> Hi there, thanks for writing.
> 
> There isn't any official support for buttons planned at the moment, but plenty of people have built and made available versions of deej that do have it in some form.
> 
> Please check out the variety of builds in the project's community showcase (linked from our homepage) or join the community Discord servers if you have more questions about building your own. Thanks!

thanks
