### ISSUE TITLE
Missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by iamjackg** [omriharel/deej#34]
Since you have a pretty clear idea of what you'd like deej to be, it would be helpful to add a `CONTRIBUTING.md` file in line with other GitHub projects.

This would act as a simple guide to tell developers how to get started with deej development, and could contain a snippet about getting in touch with you before implementing any new features.

A few good examples:
* https://gist.github.com/PurpleBooth/b24679402957c63ec426
* https://github.com/home-assistant/core/blob/dev/CONTRIBUTING.md
* https://github.com/esphome/esphome/blob/dev/CONTRIBUTING.md

**Comment by omriharel** [comment]
Fixed in d0bd8ec

**Comment by iamjackg** [comment]
Looks perfect! Thanks for putting this together!
