### ISSUE TITLE
Volume going up and down like crazy

### ISSUE THREAD

**Issue by dgroenheide** [omriharel/deej#43]
Hello,

Just as the title says, it happens when I start up the software or debug software.
The volume is going from 0 to 100 to 0 etc very fast.
how do I fix this issue?

this is my log:
[deej-latest-run.log](https://github.com/omriharel/deej/files/7228025/deej-latest-run.log)

**Comment by omriharel** [comment]
Hi there @DJVibezzz, thanks for writing.

It sounds like there is a wiring issue with the potentiometers you're using. The best way to get accurate and effective help with this kind of issue is to join our Discord server, where we have a dedicated channel to helping people solve this type of problem (which is especially useful if this is your first electronics/Arduino project).

It's also a good idea to read through our [FAQ](https://discord.com/channels/702940502038937667/703517816447565884/743193392531374112), where you'll find a detailed explanation for how to troubleshoot deej's hardware components using the serial monitor.

Please let me know if you have any additional questions. Thanks!
