### ISSUE TITLE
Teamspeak 3 client not controllable

### ISSUE THREAD

**Issue by gidsch** [omriharel/deej#53]
Hello,

I discovered deej a few days ago and i love it.

Unfortunately Teamspeak does not work.
According to the task manager the process is called ts3client_win64.exe

I also tried "deej.current", which works fine for all applications except teamspeak.

**Comment by ilbalta** [comment]
Teamspeak works fine for me. Have you verified the potentiometer works correctly?

**Comment by gidsch** [comment]
Yes all the potentiometer work fine and i can controll other applications except teamspeak.
deej.current also doesnt work for teamspeak but for others

**Comment by omriharel** [comment]
Hey there @gidsch, thanks for writing. I'm glad you like deej!

Is it possible that the version of Teamspeak you're using relies on a different process specifically for audio? Some apps do that.

If you want to be sure, you can run the debug version of deej while Teamspeak has an active audio session and see in the console output whether deej finds it and under what name. There's an explanation for how to do this in our FAQ [here](https://github.com/omriharel/deej/blob/master/docs/faq/faq.md#how-can-i-find-the-exe-name-of-insert-app-here) (see option 2).

**Comment by gidsch** [comment]
Thank you for your answers.
I have found the problem - quite stupid.

Windows always shows full volume in the sound mixer and since I was alone in Teamspeak for testing I didn't notice it.

But everything works as intended
