### ISSUE TITLE
Volume Control Reset Issue with TIDAL

### ISSUE THREAD

**Issue by ghost** [omriharel/deej#73]

**Comment by GAMZPRISM2** [comment]
Just a side note I think this could be because TIDALPlayer.exe possibly restarts whenever a new song is played? but just a theory , and therefore the application deej is looking for no longer exists (at least that specific version of it)

**Comment by GAMZPRISM2** [comment]
Just a side note I just looked at the code under session_windows.go and it seems the process is identified by its process id, so I checked whether the process id changed after each song and it doesn't, the only possibly important identifier that changed is Session from #1 to 1, full info on TIDALPlayer.exe : 

First song: TIDALPlayer.exe PID: 15172  Session Name: Console  Session: #1  Mem Usage: 53,944 K
Second song:TIDALPlayer.exe PID: 15172  Session Name: Console  Session:  1  Mem Usage: 53,292 K

**Comment by ghost** [comment]
I have realised that this is a fault of TIDAL and not deej
