### ISSUE TITLE
BLE on ESP32 

### ISSUE THREAD

**Issue by BacaR00T** [omriharel/deej#74]
Does someone have some experience with getting this running thru [bluetooth on esp32](https://github.com/T-vK/ESP32-BLE-Keyboard)? I'm just getting some dependencies ready but it would be awesome to harvest some more knowlage! <br>
If you can provide some info please go on! Thanks <3

**Comment by omriharel** [comment]
Hi there @BacaR00T, thanks for writing! I apologize for the delay in responding.

Any luck with this yet? I believe it should be relatively easy to adjust the Arduino sketch to work on that board, and the only missing thing other than that would be for the Bluetooth to act a serial port. Which I believe is a thing, though I don't know much about it.

Please feel free to re-open or add more details if you have them. Thanks!
