### ISSUE TITLE
You got mentioned by LTT :)

### ISSUE THREAD

**Issue by LorenDB** [omriharel/deej#78]
If you didn't see this yet, here you go: https://www.youtube.com/watch?v=8BxVi6YiicQ Have fun with the influx of new users!

**Comment by omriharel** [comment]
Hi @LorenDB, thanks for writing! 

It was very quickly apparent that the project got covered, as it came together with a _flood_ of new stars on GitHub as well as new users on our [community Discord server](https://discord.gg/nf88NJu) :)

I'm really glad to see the project gain this kind of traction, and I'm here to ensure its growth, with a big focus on its wonderful community. I also intend to continue supporting it with more updates and bug fixes down the line.

Thanks for the acknowledgement! 🥳

**Comment by LorenDB** [comment]
Sure, just wanted to make sure you were aware :)
