### ISSUE TITLE
Support for motorized sliders?

### ISSUE THREAD

**Issue by SOUPrayer** [omriharel/deej#79]
Hi! I saw two closed issues in the past asking about motorized sliders, but since it has been 3 and a bit years, wanted to check if anything changed/planned about this.

Personally think it would be pretty cool to create an open source GoXLR like volume control. Any chance this might be added in future?

edit: sorry I couldn't find a way to label it appropriately

**Comment by alex-pantea** [comment]
Not affiliated at all with deej, just my two cents:

Controlling motorized faders will require two-way communication.

The inspiration behind my repo was to have an open-source GoXLR, feel free to check it out.
Sorry if I shouldn’t be posting to another project within issues.
https://github.com/alex-pantea/ControlPanel

This is a very small niche, so it’s hard to say when, or even if there is enough interest from users, to add this level of customized support.

**Comment by omriharel** [comment]
Hi @SOUPrayer, thanks for writing!

I would be happy to refer you to @alex-pantea's project here. My reasoning for not wanting to include support for this in the main version of deej is that while it's very cool, it's still a niche and would make the project less friendly for beginners, which contradicts with a [core goal](https://github.com/omriharel/deej/blob/master/docs/CONTRIBUTING.md#project-audience) of mine to keep it as simple and beginner-friendly as possible.

It would be possible to fork deej and implement this in the context of the project, and it could definitely live as its own fork that takes advantage of many of the things already built into deej. But it also totally makes sense to do it as its own separate, more ambitious project such as Alex's!

**Comment by mimikm** [comment]
> Hi! I saw two closed issues in the past asking about motorized sliders, but since it has been 3 and a bit years, wanted to check if anything changed/planned about this.
> 
> Personally think it would be pretty cool to create an open source GoXLR like volume control. Any chance this might be added in future?
> 
> edit: sorry I couldn't find a way to label it appropriately

I'm working on similar controller with motorized sliders for purpose of memorising fader positions with ability to retrieve pre-set for certain ,game, application. Faders will not react on change of volume in windows, it will still works over serial like in @omriharel 's controller
