### ISSUE TITLE
Send current value of the slider + level meter

### ISSUE THREAD

**Issue by fensoft** [omriharel/deej#82]
Hi,

I want to use rotary encoder + led ring like https://modwiggler.com/forum/viewtopic.php?t=217920

Do you thing it's possible to send the current value of the slider with it's level ?

Thanks !

**Comment by omriharel** [comment]
Hi there @fensoft, thanks for writing!

It's definitely possible to make deej work with rotary encoders, but it's not inherently supported in the main version of deej which is aimed only for use with potentiometers.

I recommend you to check out a fork with encoder support such as [Orotavia/deej](https://github.com/Orotavia/deej), or to ask around in the `#coding-help` channel on our [community Discord server](https://discord.gg/nf88NJu) to help you set something similar up for yourself.

Good luck :)

**Comment by fensoft** [comment]
I'm speaking about the go windows client, not the arduino software.
I just want some kind of feedback from the serial port.

Thanks !

**Comment by omriharel** [comment]
Ah, you would need two-way communication for that. This is outside my scope, but you can try to look for a fork which does this or ask around in the Discord :)
