### ISSUE TITLE
Question: VB Audio Potato

### ISSUE THREAD

**Issue by The8bitRebel** [omriharel/deej#84]
Hi There, I am looking at using your amazing project, but first wanted to check if I am able to program faders and buttons to control faders and buttons in VB Audio Potato and what limitations there might be (if any)?

**Comment by omriharel** [comment]
Hello @The8bitRebel, thank you for writing and for the kind words. 

I can't give you a definite answer for VB Audio Potato, but the general guideline is as such: if you can control something via a slider in Windows mixer, you can very likely control it with deej. If that software does its own internal mix that it manages internally then no, not currently.

Please let me know if you have any other questions. Thanks!
