### ISSUE TITLE
Open and close quickly without any error messages

### ISSUE THREAD

**Issue by dumaster** [omriharel/deej#85]
Is this behavior normal when the Arduino is not connected to USB? Shouldn't it display an error message stating that it was not possible to connect to the specified port ???

I'm using the latest build !!!

Wouldn't it be interesting when it doesn't find the COM to open a window with the option to reconnect and close ???

Congratulations on the project and thanks for the space to suggest improvements !!!

**Comment by omriharel** [comment]
Hi @dumaster, thanks for writing.

deej currently doesn't have a GUI, but you can run its debug version (also available in the releases page) in a command terminal to see the logs there. In addition, there is a Windows notification whenever deej fails to connect - is it possible you have system notifications turned off, or Do Not Disturb, or similar?

Finally, the release version of deej creates a log file for the last run - you should be able to see connection errors there too.

Please let me know if you have any questions. Thanks!

**Comment by dumaster** [comment]
Thanks for the quick response, this project of yours is a fantastic idea, I'm here now testing it with a potentiometer just to understand how it works !!!

My notifications are actually silenced, my fault, I opened the notifications side menu and it was there the alert of disconnected COM, a suggestion if you find it interesting would be when it doesn't find the COM it opens a pop-up also warning that it couldn't communicate with the COM configured giving two alternatives of clicks buttons which would be to Exit and Reconnect !!!

I had other doubt ( this was motive of my curiosity and quickly assembled an Arduino UNO with a potentiometer to test ) was if some other software in background or the user changed the volume on the mixer, would the volume remain applied until you moved the slider or if after time a while a it would check the value of the slider comparing it with the computer and detecting a difference, if found difference he adjusted the volume again to the Slider value , and indeed, if the volume was changed outside of the deej, the volume will remain changed until you change the slider for that application that had the volume changed, then a second suggestion would be to have an option in the configuration file where you enable the application on the host from time to time ( perhaps a adjustable time ) to check and compare the volumes and if it finds any difference, it returns the volumes in the mixer to be the same as the sliders !!!!!!

But these are cosmetic suggestions, your project already works very well, I really liked the initiative of this project, it was something that was missing for many users like me who want an easy command close to their hands for the entire Windows volume system, congratulations on the project !!!

Thanks @omriharel

Edward.

**Comment by omriharel** [comment]
Hi @dumaster, thanks for the kind words about the project.

I will address both your suggestions:

- There is currently no GUI at all to deej, so it is not possible to bring up a dialog or other type of window. There will eventually be a full GUI, which will of course indicate about any connection issue and offer guidance on how to solve it.
- The behavior you've described is fully intentional. It is both for performance (responding to user pot changes, as opposed to continuously polling the volumes of running apps), and to allow users to change the volume in software if they need to (without having it instantly overridden). I don't have current plans to make it configurable.
