### ISSUE TITLE
Bluetooth compatibility

### ISSUE THREAD

**Issue by FriediDaDude** [omriharel/deej#86]
Is it possible to make this project wireless and use the bluethooth of my Arduino® Nano 33 IoT?
Im new to coding but is it possible to just change the COM_port in the config.yaml after connecting the arduino with the bluethooth of my pc ?

**Comment by omriharel** [comment]
Hi @FriediDaDude, thanks for writing.

It should be possible, but it's outside of the project scope. You may be able to work out something that uses Serial over Bluetooth but it might take a bit of tinkering. Good luck!
