### ISSUE TITLE
Discord invitation Link doesn´t work

### ISSUE THREAD

**Issue by timbslr** [omriharel/deej#91]
The discord invitation link doesn´t work for me. I don´t know if it's only a personal issue or if others have the same. Could you have a look at it? If it´s only me, can you send me a new link? Thanks!

**Comment by omriharel** [comment]
Hi @CodingFactoryT, the Discord link in the project page is a fully public invite that's used by dozens of people every day to join the community server. I believe it's on your end, but I don't have any details (such as a username) that I can use to investigate why you're unable to use it.

**Comment by timbslr** [comment]
It worked after a few more tries.
