### ISSUE TITLE
Deej.exe in autostart

### ISSUE THREAD

**Issue by timbslr** [omriharel/deej#92]
How can I start the deej.exe program automatically after the startup of Windows? I already put the dee.exe and the configuration file into the Windows startup folder, but it doesn´t seem to work.

**Comment by omriharel** [comment]
Hi @CodingFactoryT, thanks for writing again.

The method you described won't work - please check the instructions for this that we have under the [Download and installation](https://github.com/omriharel/deej?tab=readme-ov-file#download-and-installation) section of the project README.
