### ISSUE TITLE
Apple Music Not Working 

### ISSUE THREAD

**Issue by Tyler-Gaston** [omriharel/deej#94]
As the title suggests, I can not get deej to adjust the volume of the Apple Music app. The new Apple Music app is a Windows store-downloaded app, so I am not sure if that is affecting my issue. I am using a slider that I know works, so if the issue is on my end it is likely due to my configuration. I have the config set to AppleMusic.exe and have also tried Apple Music.exe. 

Has anyone experienced this or know what I might be doing wrong?

**Comment by omriharel** [comment]
Hi there @Tyler-Gaston, thanks for writing.

Please have a look at [this FAQ entry](https://github.com/omriharel/deej/blob/master/docs/faq/faq.md/#how-can-i-find-the-exe-name-of-insert-app-here) and see if it helps you locate the correct process name to use for the app. Please note that you must run deej in debug mode **while the app is playing audio**.

Let me know if that helps!

**Comment by Tyler-Gaston** [comment]
@omriharel Thanks for the fast reply. After looking at the FAQ, I realized the audio was on a secondary process. For future Apple Music Users on Windows, the process is called AMPLibraryAgent.exe.
