### ISSUE TITLE
Control individual volumes of users in discord

### ISSUE THREAD

**Issue by DanForever** [omriharel/deej#95]
In discord you can click on a person in the voice channel you're in and adjust their volume from 0 to 100 (default) to 200.
I'd love to be able to do this with deej

I can imagine either mapping the inputs to the order of the users in the voice channel (so user1, user2 etc) or explicitly naming people (possibly also by server, so that you can create different arrangements for each server you're on in discord)

The way to go is probably RPC, but it's in some form of closed beta, but maybe we'd get lucky?
I'm also down to help you implement this feature if you decide to go ahead with it
https://discord.com/developers/docs/topics/rpc

**Comment by omriharel** [comment]
Hi @DanForever, thanks for writing.

This suggestion is cool but is ultimately outside what I currently consider to be in scope for the project. This may be revisited at a later point in the future, if other types of app-specific advanced bindings become a reality.

If you would like to have a go at implementing it, as per the project's [contribution guidelines](https://github.com/omriharel/deej/blob/master/docs/CONTRIBUTING.md) I encourage you to do that in a fork of your own.

Please let me know if you have any other questions. Thanks!
